import Head from "next/head";
import React from "react";

type Props = {
  children?: React.ReactNode;
  title?: string;
};
export const metadata = {
  title: {
    default: "E-Commerce Web App",
    template: "%s | Acme",
  },
  description: "Generated by create next app",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript"],
  authors: [{ name: "Seb" }, { name: "Josh", url: "https://nextjs.org" }],
  colorScheme: "dark",
  creator: "Jiachi Liu",
  publisher: "Sebastian Markbåge",
  alternates: {},
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "Next.js",
    description: "The React Framework for the Web",
    type: "article",
    publishedTime: "2023-01-01T00:00:00.000Z",
    authors: ["Seb", "Josh"],
  },
};
const Layout = ({ children, title = "Profilim" }: Props) => {
  return (
    <>
      <div>{children}</div>
    </>
  );
};

export default Layout;
