import Image from "next/image";

import Layout from "../components/layout/Layout";
import Head from "next/head";

import Link from "next/link";
import { base64SolidImage } from "../utility/SolidImage";
import dynamic from "next/dynamic";

const SlickSlider = dynamic(() => import("../components/SlickSlider"), {
  ssr: false,
});
const PlayerHome = dynamic(() => import("../components/PlayerHome"), {
  ssr: false,
});

const ShopTheLookSlider = dynamic(
  () => import("../components/ShopTheLookSlider"),
  { ssr: false }
);
const SosyalPlatform = dynamic(
  () => import("../components/misc/SosyalPlatform"),
  {
    ssr: false,
  }
);

export const metadata = {
  title: {
    default: "E-Commerce Web App",
    template: "%s | Acme",
  },
  description: "Generated by create next app",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript"],
  authors: [{ name: "Seb" }, { name: "Josh", url: "https://nextjs.org" }],
  colorScheme: "dark",
  creator: "Jiachi Liu",
  publisher: "Sebastian Markbåge",
  alternates: {},
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "Next.js",
    description: "The React Framework for the Web",
    type: "article",
    publishedTime: "2023-01-01T00:00:00.000Z",
    authors: ["Seb", "Josh"],
  },
};
export default function Home() {
  return (
    <Layout title="">
      <Head>
        <title>Perspective</title>
        <meta name="description" content="deneeme desription" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page ">
        <div className="mx-auto w-full px-2 lg:px-10">
          <div className="block">
            <Link className="block" href={"/category/yeni-sezon"}>
              <Image
                src="/assets/Perspective-SS23-Web-Slider-1366x630px.jpg"
                width={1366}
                height={630}
                alt="banner"
                priority={true}
                className="w-full"
                blurDataURL={`data:image/svg+xml;base64,${base64SolidImage(
                  "blue"
                )}`}
              />
            </Link>
          </div>
        </div>

        <div className="mx-auto w-full px-2 lg:px-8 my-5  min-h-[294px]">
          <SlickSlider />
        </div>
        <div className="block min-h-[240px]">
          <PlayerHome />
        </div>
        <div className="block my-5 min-h-[500px]">
          <ShopTheLookSlider />
        </div>
        <div className="mx-auto w-full px-2 lg:px-10 my-16 items-center justify-center">
          <SosyalPlatform />
        </div>
      </main>
    </Layout>
  );
}
