import Image from "next/image";

import { Montserrat, Poppins, Inter } from "next/font/google";
import Layout from "../components/layout/Layout";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-pappins",
});
export const metadata = {
  title: {
    default: "E-Commerce Web App",
    template: "%s | Acme",
  },
  description: "Generated by create next app",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript"],
  authors: [{ name: "Seb" }, { name: "Josh", url: "https://nextjs.org" }],
  colorScheme: "dark",
  creator: "Jiachi Liu",
  publisher: "Sebastian Markbåge",
  alternates: {},
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "Next.js",
    description: "The React Framework for the Web",
    type: "article",
    publishedTime: "2023-01-01T00:00:00.000Z",
    authors: ["Seb", "Josh"],
  },
};
export default function Home() {
  return (
    <Layout title="">
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        DENEME
        <div className={`${montserrat.className} `}>
          Footer İ ş Ğ Ü Ö Ç ç i ı
        </div>
        <div className={`${poppins.className} `}>Footer İ ş Ğ Ü Ö Ç ç i ı</div>
      </main>
    </Layout>
  );
}
